apiVersion: core.oam.dev/v1beta1
kind: PolicyDefinition
metadata:
  name: vlim-allowed-config
spec:
  schematic:
    cue:
      template: |
        patch: {
          // Enforce allowed VM sizes
          if context.app.spec.components[0].properties.instanceType != _|_ {
            allowed: ["t2.micro", "ecs.t5-lc2m1.nano", "S5.MEDIUM4"]
            if context.app.spec.components[0].properties.instanceType notin allowed {
              err: "Instance type not allowed by VLIMF governance"
            }
          }
        }
