apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: vlimf-sample-web
  namespace: default
spec:
  components:
    - name: web
      type: webservice
      properties:
        image: nginx
        ports:
          - port: 80
      traits:
        # later you’ll inject VLIMF policies here, like provider selection, failover, etc.
        - type: vlimf-policy
          properties:
            strategy: multi-cloud
